name = "ProceduralNoise"
uuid = "3aba9546-43d6-4ec1-9542-6d3f8f2a5c7f"
authors = ["Damian <dcamenisch98@gmail.com> and contributors"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.9"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
