
function value_noise(x)
    l, r, dx = bounds(x)
    vl = random_from(l)
    vh = random_from(h)
    return interpolate(d, vl, vh)
end

function value_noise(x, y)
    l, r, dx = bounds(x)
    b, t, dy = bounds(y)
    tl = random_from(t, l)
    tr = random_from(t, r)
    bl = random_from(b, l)
    br = random_from(b, r)
    return interpolate(dx, dy, tl, tr, bl, br)
end

function value_noise(x, y, z)
    l, r, dx = bounds(x)
    b, t, dy = bounds(y)
    a, o, dz = bounds(z)
    atl = random_from(a, t, l)
    atr = random_from(a, t, r)
    abl = random_from(a, b, l)
    abr = random_from(a, b, r)
    otl = random_from(o, t, l)
    otr = random_from(o, t, r)
    obl = random_from(o, b, l)
    obr = random_from(o, b, r)
    return interpolate(dx, dy, dz, atl, atr, abl, abr, otl, otr, obl, obr)
end

function value_noise(x, y, z, w)
    l, r, dx = bounds(x)
    b, t, dy = bounds(y)
    a, o, dz = bounds(z)
    w1, w2, dw = bounds(w)
    atl1 = random_from(a, t, l, w1)
    atr1 = random_from(a, t, r, w1)
    abl1 = random_from(a, b, l, w1)
    abr1 = random_from(a, b, r, w1)
    otl1 = random_from(o, t, l, w1)
    otr1 = random_from(o, t, r, w1)
    obl1 = random_from(o, b, l, w1)
    obr1 = random_from(o, b, r, w1)
    atl2 = random_from(a, t, l, w2)
    atr2 = random_from(a, t, r, w2)
    abl2 = random_from(a, b, l, w2)
    abr2 = random_from(a, b, r, w2)
    otl2 = random_from(o, t, l, w2)
    otr2 = random_from(o, t, r, w2)
    obl2 = random_from(o, b, l, w2)
    obr2 = random_from(o, b, r, w2)
    return interpolate(dx, dy, dz, dw, atl1, atr1, abl1, abr1, otl1, otr1, obl1, obr1, atl2, atr2, abl2, abr2, otl2, otr2, obl2, obr2)
end

